cart/urls.py
from django.urls import path

from cart.views import cart_detail, cart_add, cart_remove, cart_add_one, cart_remove_one, clear_cart

app_name = 'cart'

urlpatterns = [
    path('', cart_detail, name='cart_detail'),
    path('add/<int:pk>/', cart_add, name='cart_add'),
    path('remove/<int:pk>/', cart_remove, name='cart_remove'),
    path('add_one/<int:pk>/', cart_add_one, name='cart_add_one'),
    path('remove_one/<int:pk>/', cart_remove_one, name='cart_remove_one'),
    path('clear/', clear_cart, name='clear_cart'),
]

catalog/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path
from catalog.views import *

app_name = 'catalog'

urlpatterns = [
    path('', Product_Catalog.as_view(), name='catalog_view'),
    path('delete_review/<int:pk>/', Delete_Review.as_view(), name='delete_review'),
    path('create_product/', Create_Product.as_view(), name='create_product'),
    path('detail_product/<int:pk>/<str:slug>/', Product_Detail.as_view(), name='product_detail'),
    path('update_product/<int:pk>/', Update_Product.as_view(), name='update_product'),
    path('delete_product/<int:pk>/', Delete_Product.as_view(), name='delete_product'),

    path('brand_list/', Brand_List.as_view(), name='brand_list'),
    path('create_brand/', Create_Brand.as_view(), name='create_brand'),
    path('detail_brand/<int:pk>/', Brand_Detail.as_view(), name='brand_detail'),
    path('update_brand/<int:pk>/', Update_Brand.as_view(), name='update_brand'),
    path('delete_brand/<int:pk>/', Delete_Brand.as_view(), name='delete_brand'),

    path('create_category/', Create_Category.as_view(), name='create_category'),
    path('delete_category/<int:pk>/', Delete_Category.as_view(), name='delete_category'),
    path('translate_category/<int:pk>/', Translate_Category.as_view(), name='translate_category'),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

coupon/urls.py
from django.urls import path
from .views import coupon_apply

app_name = 'coupon'

urlpatterns = [
    path('apply/', coupon_apply, name='apply'),
]

order/urls.py
from django.urls import path, re_path
from order.views import Create_Order, Order_Detail, Order_History, admin_order_detail, admin_order_pdf


app_name = 'order'

urlpatterns = [
    path('', Create_Order.as_view(), name='create_order'),
    path('order_history/', Order_History.as_view(), name='order_history'),
    path('order_detail/<int:pk>/', Order_Detail.as_view(), name='order_detail'),
    path('admin/<int:pk>/', admin_order_detail, name='admin_order_detail'),
    path('admin/order/<int:pk>/pdf/', admin_order_pdf, name='admin_order_pdf'),
]

pet_project/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf.urls.i18n import i18n_patterns
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = i18n_patterns(
    re_path(r'^admin/', admin.site.urls),
    re_path(r'^', include("main_app.urls", namespace='main_app')),
    re_path(r'^catalog/', include("catalog.urls", namespace='catalog')),
    re_path(r'^cart/', include("cart.urls", namespace='cart')),
    re_path(r'^order/', include("order.urls", namespace='order')),
    re_path(r'^coupon/', include('coupon.urls', namespace='coupon')),
    re_path(r'^rosetta/', include('rosetta.urls')),
)

urlpatterns += [
    path('payment/', include('payment.urls', namespace='payment'))
]# отдельно чтобы не было в i18n_patterns

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cart/models.py
from django.contrib.auth import get_user_model
from django.db import models

# Create your models here.

cart/forms.py
from django import forms
from django.utils.translation import gettext_lazy as _

class CartAddProductForm(forms.Form):
    quantity = forms.IntegerField(initial=1, min_value=0, label=_('Quantity'))
    update = forms.BooleanField(required=False, initial=False, widget=forms.HiddenInput, label=_('Update'))

cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views import View
from django.views.decorators.http import require_POST
from django.utils.translation import gettext_lazy as _
from cart.cart_session import Cart
from cart.forms import CartAddProductForm
from catalog.models import Product
from catalog.recommender import Recommender
from coupon.forms import CouponApplyForm

# Create your views here.

@require_POST
def cart_add(request, pk):
    cart = Cart(request)
    try:
        product = Product.objects.get(pk=pk)
        form = CartAddProductForm(request.POST)
        if form.is_valid():
            cart.add(product=product,
                     quantity=form.cleaned_data['quantity'],
                     update_quantity=form.cleaned_data['update'])
        return redirect('cart:cart_detail')
    except Product.DoesNotExist:
        error = _('There is no such product')
        return render(request, 'cart/error_page.html', {'error':error})

def cart_remove(request, pk):
    cart = Cart(request)
    try:
        product = Product.objects.get(pk=pk)
        cart.remove(product)
        return redirect('cart:cart_detail')
    except Product.DoesNotExist:
        error = _('There is no such product')
        return render(request, 'cart/error_page.html', {'error':error})

def cart_detail(request):
    cart = Cart(request)
    coupon_apply_form = CouponApplyForm()
    r = Recommender()
    cart_products = [item['product'] for item in cart]
    if (cart_products):
        recommended_products = r.suggest_products_for(cart_products, max_results=4)
    else:
        recommended_products = []
    context = {'cart': cart, 'coupon_apply_form': coupon_apply_form, 'recommended_products': recommended_products}
    return render(request, 'cart/cart_detail.html', context)

def cart_add_one(request, pk):
    cart = Cart(request)
    try:
        product = Product.objects.get(pk=pk)
        cart.add_one(product)
        return redirect('cart:cart_detail')
    except Product.DoesNotExist:
        error = _('There is no such product')
        return render(request, 'cart/error_page.html', {'error':error})

def cart_remove_one(request, pk):
    cart = Cart(request)
    try:
        product = Product.objects.get(pk=pk)
        cart.remove_one(product)
        return redirect('cart:cart_detail')
    except Product.DoesNotExist:
        error = _('There is no such product')
        return render(request, 'cart/error_page.html', {'error':error})

def clear_cart(request):
    cart = Cart(request)
    cart.clear()
    return redirect('cart:cart_detail')

cart/templates/cart/cart_detail.html
{% load static %}
{% load i18n %}

<html lang="en">
<head>
    <title>{% block title %}{% trans 'Cart details' %}{% endblock title %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
</head>
<body class="container mt-4">

    <a href="{% url 'catalog:catalog_view' %}" class="btn btn-secondary mb-3">{% trans 'Back' %}</a>

    {% block content %}
    <h1 class="mb-4">{% trans 'Your shopping cart' %}</h1>

    {% for item in cart %}
        <hr>
        <div class="product-item row mb-3 align-items-center">
            <div class="col-md-6">
                <p class="mb-1 font-weight-bold">{{ item.product.name }} ({{ item.quantity }})</p>
                <p class="mb-1">{% translate 'Price' %}: ${{ item.product.price }}</p>
                <p class="mb-1">{{ item.total_item_cost }}</p>
            </div>
            <div class="col-md-6 text-right">
                <a href="{% url 'cart:cart_add_one' pk=item.product.pk %}" class="btn btn-sm btn-success">+</a>
                <a href="{% url 'cart:cart_remove_one' pk=item.product.pk %}" class="btn btn-sm btn-warning">-</a>
                <a href="{% url 'cart:cart_remove' pk=item.product.pk %}" class="btn btn-sm btn-danger">{% trans 'Remove' %}</a>
            </div>
        </div>
    {% empty %}
        <p>{% trans 'Your cart is empty' %}</p>
    {% endfor %}

    {% if cart.coupon %}
        <div class="table-responsive">
            <table class="table">
                <tbody>
                    <tr class="subtotal">
                        <td>{% trans 'Subtotal' %}</td>
                        <td class="text-right">${{ cart.get_total_price }}</td>
                    </tr>
                    <tr>
                        <td>
                            "{{ cart.coupon.code }}" {% trans 'coupon' %}
                            ({{ cart.coupon.discount }}% off)
                        </td>
                        <td class="text-right text-danger">
                            - ${{ cart.get_discount|floatformat:"2" }}
                        </td>
                    </tr>
                </tbody>
            </table>
        </div>
    {% endif %}

    <hr>

    <form action="{% url 'coupon:apply' %}" method="post" class="form-inline mb-3">
        {% csrf_token %}
        <div class="form-group mx-sm-3 mb-2">
            {{ coupon_apply_form.code }}
        </div>
        <button type="submit" class="btn btn-primary mb-2">{% trans 'Apply' %}</button>
    </form>

    {% if messages %}
        <div class="alert alert-info">
            <ul class="mb-0">
                {% for message in messages %}
                    <li>{{ message }}</li>
                {% endfor %}
            </ul>
        </div>
    {% endif %}

    <p class="font-weight-bold">{% trans 'Total price' %}: ${{ cart.get_total_price_after_discount|floatformat:"2" }}</p>
    <hr>

<div class="row mb-3">
    <div class="col">
        <a href="{% url 'order:create_order' %}" class="btn btn-success">{% trans 'Place order' %}</a>
        <form action="{% url 'cart:clear_cart' %}" method="get" style="display: inline-block;">
            {% csrf_token %}
            <button type="submit" class="btn btn-danger">{% trans 'Clear' %}</button>
        </form>
    </div>
</div>

    {% if recommended_products %}
        <div class="recommendations mb-4">
            <h3>{% translate 'Similar products' %}</h3>
            <div class="row">
                {% for p in recommended_products %}
                    <div class="col-md-3 mb-3">
                        <div class="card">
                            {% if p.image %}
                                <img src="{{ p.image.url }}" class="card-img-top" alt="Product Image" height="250">
                            {% else %}
                                <img src="{% static 'catalog/img/photo_2024-04-04_14-55-47.jpg' %}" class="card-img-top" alt="Product Image" height="250">
                            {% endif %}
                            <div class="card-body text-center">
                                <a href="{% url 'catalog:product_detail' pk=p.pk slug=p.slug %}" class="card-link">{{ p.name }}</a>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>
    {% endif %}
    {% endblock content %}

    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.3/dist/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
</body>
</html>  

cart/templates/cart/error_page.html
{% extends 'cart/cart_detail.html' %}
{% load static %}
{% load i18n %}

{% block content %}
<div class="alert alert-danger mt-4" role="alert">
    <h4 class="alert-heading">{% trans 'We apologize' %}</h4>
    <p>{{ error }}</p>
</div>
{% endblock content %}