cart/urls.py
from django.urls import path

from cart.views import cart_detail, cart_add, cart_remove, cart_add_one, cart_remove_one, clear_cart

app_name = 'cart'

urlpatterns = [
    path('', cart_detail, name='cart_detail'),
    path('add/<int:pk>/', cart_add, name='cart_add'),
    path('remove/<int:pk>/', cart_remove, name='cart_remove'),
    path('add_one/<int:pk>/', cart_add_one, name='cart_add_one'),
    path('remove_one/<int:pk>/', cart_remove_one, name='cart_remove_one'),
    path('clear/', clear_cart, name='clear_cart'),
]

catalog/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path
from catalog.views import *

app_name = 'catalog'

urlpatterns = [
    path('', Product_Catalog.as_view(), name='catalog_view'),
    path('delete_review/<int:pk>/', Delete_Review.as_view(), name='delete_review'),
    path('create_product/', Create_Product.as_view(), name='create_product'),
    path('detail_product/<int:pk>/<str:slug>/', Product_Detail.as_view(), name='product_detail'),
    path('update_product/<int:pk>/', Update_Product.as_view(), name='update_product'),
    path('delete_product/<int:pk>/', Delete_Product.as_view(), name='delete_product'),

    path('brand_list/', Brand_List.as_view(), name='brand_list'),
    path('create_brand/', Create_Brand.as_view(), name='create_brand'),
    path('detail_brand/<int:pk>/', Brand_Detail.as_view(), name='brand_detail'),
    path('update_brand/<int:pk>/', Update_Brand.as_view(), name='update_brand'),
    path('delete_brand/<int:pk>/', Delete_Brand.as_view(), name='delete_brand'),

    path('create_category/', Create_Category.as_view(), name='create_category'),
    path('delete_category/<int:pk>/', Delete_Category.as_view(), name='delete_category'),
    path('translate_category/<int:pk>/', Translate_Category.as_view(), name='translate_category'),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main_app/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, re_path

from main_app.views import main, register_view, login_view, logout_view, profile

app_name = 'main_app'

urlpatterns = [
    path('', main, name='main'),
    path('register/', register_view, name='register'),
    path('login/', login_view, name='login'),
    path('logout/', logout_view, name='logout'),
    path('profile/', profile, name='profile'),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pet_project/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf.urls.i18n import i18n_patterns
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = i18n_patterns(
    re_path(r'^admin/', admin.site.urls),
    re_path(r'^', include("main_app.urls", namespace='main_app')),
    re_path(r'^catalog/', include("catalog.urls", namespace='catalog')),
    re_path(r'^cart/', include("cart.urls", namespace='cart')),
    re_path(r'^order/', include("order.urls", namespace='order')),
    re_path(r'^coupon/', include('coupon.urls', namespace='coupon')),
    re_path(r'^rosetta/', include('rosetta.urls')),
)

urlpatterns += [
    path('payment/', include('payment.urls', namespace='payment'))
]# отдельно чтобы не было в i18n_patterns

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main_app/models.py
from django.contrib.auth.base_user import BaseUserManager
from django.contrib.auth.models import AbstractUser, PermissionsMixin
from django.db import models
from django.utils.translation import gettext_lazy as _

# Create your models here.

class CustomUserManager(BaseUserManager):

    def create_user(self, username, password, email, first_name, last_name, **extra_fields):
        if not email:
            raise ValueError('email must be entered')
        else:
            email = self.normalize_email(email)
            is_superuser = extra_fields.get('is_superuser')
            is_staff = extra_fields.get('is_staff')
            user = self.model(username=username, email=email, first_name=first_name, last_name=last_name, is_superuser=is_superuser, is_staff=is_staff)
            user.set_password(password)
            user.save()
            return user

    def create_superuser(self, password, email, username=None, first_name=None, last_name=None, **extra_fields):
        username = input("Enter username: ")
        first_name = input('Enter first name: ')
        last_name = input('Enter last name: ')
        extra_fields.setdefault('is_active', True)
        extra_fields.setdefault('is_superuser', True)
        extra_fields.setdefault('is_staff', True)
        return self.create_user(username, password, email, first_name, last_name, **extra_fields)

class User(AbstractUser, PermissionsMixin):
    username = models.CharField(verbose_name=_('username') ,max_length=100, unique=False)
    email = models.EmailField(verbose_name=_('email') ,unique=True)
    avatar = models.ImageField(verbose_name=_('avatar') ,upload_to='avatars/', blank=True)
    first_name = models.CharField(verbose_name=_('first name') ,max_length=100)
    last_name = models.CharField(verbose_name=_('last name') ,max_length=100)
    is_staff = models.BooleanField(default=False)
    is_active = models.BooleanField(default=True)
    objects = CustomUserManager()

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    def __str__(self):
        return self.username

    class Meta:
        verbose_name = _('User')
        verbose_name_plural = _('Users')

main_app/forms.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from django.utils.translation import gettext_lazy as _
from main_app.models import User

class UserForm(UserCreationForm):
    password1 = forms.CharField(widget=forms.PasswordInput(), max_length=100, label=_('password1'))
    password2 = forms.CharField(widget=forms.PasswordInput(), max_length=100, label=_('password2'))

    def check_password(self):
        password1 = self.cleaned_data['password1']
        password2 = self.cleaned_data['password2']
        if password1 == password2:
            return password1
        else:
            raise forms.ValidationError("Passwords do not match")

    def save(self, commit=True):
        user = super().save(commit=False)
        user.set_password(self.cleaned_data['password1'])
        if commit:
            user.save()
        else:
            return user

    def clean_username(self):
        # Просто возвращаем значение без проведения проверки уникальности
        return self.cleaned_data['username']

    class Meta:
        model = User
        fields = ('username', 'password1', 'password2', 'email', 'first_name', 'last_name', 'avatar',)

class LoginForm(forms.Form):
    email = forms.EmailField(label=_('email'))
    password = forms.CharField(max_length=100, widget=forms.PasswordInput(), label=_('password'))

class ProfileForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'avatar',)

main_app/views.py
from django.contrib.auth import login, authenticate, logout
from django.shortcuts import render, redirect
from main_app.forms import UserForm, LoginForm, ProfileForm
from django.utils.translation import gettext_lazy as _
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import user_passes_test

# Create your views here.

def is_authenticated(user):
    return user.is_authenticated

def main(request):
    return render(request, 'main_app/main.html', {'request': request})

def register_view(request):
    if request.method == 'POST':
        form = UserForm(data=request.POST, files=request.FILES)
        if form.is_valid():
            form.save()
            email = form.cleaned_data['email']
            password = form.cleaned_data['password1']
            user = authenticate(request=request, email=email, password=password)
            if user:
                login(request, user=user)
                return redirect('main_app:main')
        else:
            return render(request, 'main_app/login_form.html', {'form': form, 'form_name': _('Register form')})
    else:
        return render(request, 'main_app/login_form.html', {'form': UserForm(), 'form_name': _('Register form')})

def login_view(request):
    if request.method == 'POST':
        form = LoginForm(data=request.POST)
        if form.is_valid():
            email = form.cleaned_data['email']
            password = form.cleaned_data['password']
            user = authenticate(request=request, email=email, password=password)
            if user:
                login(request, user)
                return redirect('main_app:main')
            else:
                form.add_error(None, _('User was not found'))
                return render(request, 'main_app/login_form.html', {'form': form, 'form_name': _('Authentication form')})
        else:
            form.add_error(None, _('Form data is invalid'))
            return render(request, 'main_app/login_form.html', {'form': form, 'form_name': _('Authentication form')})
    else:
        form = LoginForm()
        return render(request, 'main_app/login_form.html', {'form': form, 'form_name': _('Authentication form')})

@user_passes_test(is_authenticated)
def logout_view(request):
    logout(request)
    return redirect('main_app:main')

@user_passes_test(is_authenticated)
def profile(request):
    if request.method == 'POST':
        form = ProfileForm(data=request.POST, files=request.FILES, instance=request.user)
        if form.is_valid():
            form.save()
            return redirect('main_app:main')
        else:
            return render(request, 'main_app/profile.html', {'form': form})
    else:
        form = ProfileForm(instance=request.user)
        return render(request, 'main_app/profile.html', {'form': form})

main_app/templates/main_app/login_form.html
{% extends 'main_app/main.html' %}
{% load i18n %}
{% load static %}

{% block content %}
<div class="container mt-4">
    <h1 class="mb-4">{{ form_name }}</h1>
    <form method="post" enctype="multipart/form-data" class="needs-validation" novalidate>
        {% csrf_token %}
        <div class="mb-3">
            {{ form.as_p }}
        </div>
        <button type="submit" class="btn btn-primary">{% trans 'Send' %}</button>
    </form>
</div>
{% endblock content %}

main_app/templates/main_app/main.html
{% load static %}
{% load i18n %}

<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% trans 'Main' %}{% endblock title %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'main_app/css/main.css' %}">
    <style>
        .btn {
            font-size: 1rem;
            padding: 0.5rem 1rem;
            white-space: normal;
        }

        @media (max-width: 576px) {
            .btn {
                font-size: 0.9rem;
            }
        }

        .button-container {
            display: flex;
            justify-content: center;
            flex-wrap: wrap;
            gap: 0.5rem;
        }

        .avatar {
            max-width: 100px;
            height: auto;
        }
    </style>
</head>
<body class="container mt-4">

    {% block content %}
    
    <div class="row justify-content-center text-center">
        {% if user.is_authenticated %}
            <div class="col-12 mb-4">
                <h2>{% trans 'Welcome' %} {{ request.user.username }}</h2>
                <div class="d-flex justify-content-center">
                    {% if request.user.avatar %}
                        <img src="{{ request.user.avatar.url }}" alt="Avatar" class="rounded-circle avatar">
                    {% else %}
                        <img src="{% static 'main_app/img/photo_2024-04-04_14-56-07.jpg' %}" alt="Avatar" class="rounded-circle avatar">
                    {% endif %}
                </div>
            </div>
            <div class="col-12 col-md-6 button-container mb-3">
                <a href="{% url 'main_app:logout' %}" class="btn btn-secondary">{% trans 'Exit' %}</a>
                <a href="{% url 'main_app:profile' %}" class="btn btn-primary">{% trans 'Profile' %}</a>
                <a href="{% url 'catalog:catalog_view' %}" class="btn btn-success">{% trans 'Catalog' %}</a>
            </div>
        {% else %}
            <div class="col-12 col-md-6 button-container mb-3">
                <a href="{% url 'main_app:register' %}" class="btn btn-warning">{% trans 'Register' %}</a>
                <a href="{% url 'main_app:login' %}" class="btn btn-info">{% trans 'Log in' %}</a>
            </div>
        {% endif %}
    </div>

    <div class="row justify-content-center align-items-center mt-4">
        <p class="col-auto mb-0">{% trans 'Language' %}:</p>
        <ul class="list-inline col-auto mb-0">
            {% get_current_language as LANGUAGE_CODE %}
            {% get_available_languages as LANGUAGES %}
            {% get_language_info_list for LANGUAGES as languages %}
            {% for language in languages %}
                <li class="list-inline-item">
                    <a href="/{{ language.code }}/" class="{% if language.code == LANGUAGE_CODE %}btn btn-outline-primary active{% else %}btn btn-outline-secondary{% endif %} btn-sm">
                        {{ language.name_local }}
                    </a>
                </li>
            {% endfor %}
        </ul>
    </div>

    {% endblock content %}

    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.3/dist/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>

</body>
</html>

main_app/templates/main_app/profile.html
{% extends 'main_app/main.html' %}
{% load i18n %}
{% load static %}

{% block content %}
<div class="container mt-4">
    <h1 class="mb-4">Profile</h1>
    <form method="post" enctype="multipart/form-data" class="needs-validation" novalidate>
        {% csrf_token %}
        <div class="mb-3">
            {{ form.as_p }}
        </div>
        <button type="submit" class="btn btn-primary">{% trans 'send' %}</button>
    </form>
</div>
{% endblock content %}