cart/urls.py
from django.urls import path

from cart.views import cart_detail, cart_add, cart_remove, cart_add_one, cart_remove_one, clear_cart

app_name = 'cart'

urlpatterns = [
    path('', cart_detail, name='cart_detail'),
    path('add/<int:pk>/', cart_add, name='cart_add'),
    path('remove/<int:pk>/', cart_remove, name='cart_remove'),
    path('add_one/<int:pk>/', cart_add_one, name='cart_add_one'),
    path('remove_one/<int:pk>/', cart_remove_one, name='cart_remove_one'),
    path('clear/', clear_cart, name='clear_cart'),
]

catalog/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path
from catalog.views import *

app_name = 'catalog'

urlpatterns = [
    path('', Product_Catalog.as_view(), name='catalog_view'),
    path('delete_review/<int:pk>/', Delete_Review.as_view(), name='delete_review'),
    path('create_product/', Create_Product.as_view(), name='create_product'),
    path('detail_product/<int:pk>/<str:slug>/', Product_Detail.as_view(), name='product_detail'),
    path('update_product/<int:pk>/', Update_Product.as_view(), name='update_product'),
    path('delete_product/<int:pk>/', Delete_Product.as_view(), name='delete_product'),

    path('brand_list/', Brand_List.as_view(), name='brand_list'),
    path('create_brand/', Create_Brand.as_view(), name='create_brand'),
    path('detail_brand/<int:pk>/', Brand_Detail.as_view(), name='brand_detail'),
    path('update_brand/<int:pk>/', Update_Brand.as_view(), name='update_brand'),
    path('delete_brand/<int:pk>/', Delete_Brand.as_view(), name='delete_brand'),

    path('create_category/', Create_Category.as_view(), name='create_category'),
    path('delete_category/<int:pk>/', Delete_Category.as_view(), name='delete_category'),
    path('translate_category/<int:pk>/', Translate_Category.as_view(), name='translate_category'),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

order/urls.py
from django.urls import path, re_path
from order.views import Create_Order, Order_Detail, Order_History, admin_order_detail, admin_order_pdf


app_name = 'order'

urlpatterns = [
    path('', Create_Order.as_view(), name='create_order'),
    path('order_history/', Order_History.as_view(), name='order_history'),
    path('order_detail/<int:pk>/', Order_Detail.as_view(), name='order_detail'),
    path('admin/<int:pk>/', admin_order_detail, name='admin_order_detail'),
    path('admin/order/<int:pk>/pdf/', admin_order_pdf, name='admin_order_pdf'),
]

pet_project/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf.urls.i18n import i18n_patterns
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = i18n_patterns(
    re_path(r'^admin/', admin.site.urls),
    re_path(r'^', include("main_app.urls", namespace='main_app')),
    re_path(r'^catalog/', include("catalog.urls", namespace='catalog')),
    re_path(r'^cart/', include("cart.urls", namespace='cart')),
    re_path(r'^order/', include("order.urls", namespace='order')),
    re_path(r'^coupon/', include('coupon.urls', namespace='coupon')),
    re_path(r'^rosetta/', include('rosetta.urls')),
)

urlpatterns += [
    path('payment/', include('payment.urls', namespace='payment'))
]# отдельно чтобы не было в i18n_patterns

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

order/models.py
from decimal import Decimal

from django.contrib.auth import get_user_model
from django.core.validators import MinValueValidator, MaxValueValidator
from django.db import models
from catalog.models import Product
from coupon.models import Coupon
from django.utils.translation import gettext_lazy as _

from pet_project import settings

User = get_user_model()

# Create your models here.

class Order(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name=_('User'))
    address = models.CharField(verbose_name=_('address'), max_length=100)
    first_name = models.CharField(verbose_name=_('first name'),max_length=100)
    last_name = models.CharField(verbose_name=_('last name'),max_length=100)
    city = models.CharField(verbose_name=_('city'),max_length=100)
    email = models.EmailField(verbose_name=_('email'),)
    paid = models.BooleanField(verbose_name=_('paid'),default=False)
    created = models.DateTimeField(verbose_name=_('created'),auto_now=True)
    coupon = models.ForeignKey(Coupon, related_name='orders', null=True, blank=True, on_delete=models.CASCADE, verbose_name=_('coupon'))
    discount = models.IntegerField(verbose_name=_('discount'),default=0, validators=[MinValueValidator(0), MaxValueValidator(100)])
    stripe_id = models.CharField(max_length=250, blank=True)

    def __str__(self):
        return str(self.pk)

    def total_order_cost(self):
        total_cost = sum(item.total_item_cost() for item in self)
        return total_cost - total_cost * (self.discount / Decimal('100'))

    def __iter__(self):
        for item in Order_Item.objects.filter(order=self):
            yield item

    def get_stripe_url(self):
        if not self.stripe_id:
        # никаких ассоциированных платежей
            return ''
        if '_test_' in settings.STRIPE_SECRET_KEY:
        # путь Stripe для тестовых платежей
            path = '/test/'
        else:
        # путь Stripe для настоящих платежей
            path = '/'
        return f'https://dashboard.stripe.com{path}payments/{self.stripe_id}'

    def get_discount(self):
        total_cost = self.get_total_cost_before_discount()
        if self.discount:
            return total_cost * (self.coupon.discount / Decimal(100))
        return Decimal(0)

    def get_total_cost_before_discount(self):
        return sum(item.total_item_cost() for item in self.items.all())

    def get_total_cost(self):
        total_cost = self.get_total_cost_before_discount()
        return total_cost - self.get_discount()

    class Meta:
        ordering = ('-created',)
        verbose_name = _('Order')
        verbose_name_plural = _('Orders')

class Order_Item(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE, blank=True, verbose_name=_('product'))
    order = models.ForeignKey(Order, related_name='items', on_delete=models.CASCADE, verbose_name=_('order'))
    price = models.DecimalField(verbose_name=_('price'), max_digits=10, decimal_places=2, validators=[MinValueValidator(0)])
    quantity = models.PositiveIntegerField(verbose_name=_('quantity'), default=1)

    def __str__(self):
        return str(self.pk)

    def total_item_cost(self):
        return self.price * self.quantity

    class Meta:
        ordering = ('-pk',)
        verbose_name = _('Order item')
        verbose_name_plural = _('Order items')

order/forms.py
from django import forms
from django.utils.translation import gettext_lazy as _
from order.models import Order

class OrderForm(forms.ModelForm):

    class Meta:
        fields = ('email', 'address', 'city', 'first_name', 'last_name')
        model = Order

order/views.py
import weasyprint
from django.contrib.admin.views.decorators import staff_member_required
from django.http import HttpResponse
from django.shortcuts import render, get_object_or_404
from django.template.loader import render_to_string
from django.views import View
from django.utils.translation import gettext_lazy as _
from cart.cart_session import Cart
from catalog.recommender import Recommender
from order.forms import OrderForm
from pet_project import settings
from .models import Order_Item, Order

# Create your views here.

class Order_History(View):
    def get(self, request):
        objects = Order.objects.filter(user=request.user)
        return render(request, 'order/order_history.html', {'objects':objects})

class Create_Order(View):
    def get(self, request):
        form = OrderForm()
        return render(request, 'order/order_create.html', {'form': form})

    def post(self, request):
        cart = Cart(request)
        if cart:
            form = OrderForm(request.POST)
            if form.is_valid():
                order = form.save(commit=False)
                order.user = request.user
                if cart.coupon:
                    order.coupon = cart.coupon
                    order.discount = cart.coupon.discount
                order.save()
                for item in cart:
                    Order_Item.objects.create(order=order,
                                             product=item['product'],
                                             price=item['price'],
                                             quantity=item['quantity'])
                # очистка корзины
                cart.clear()

                r = Recommender()
                products_in_order = [item['product'] for item in cart]
                r.products_bought(products_in_order)
                request.session['order_pk'] = order.pk
                return render(request, 'payment/process.html', {'order': order})
        else:
            error = _('Yor cart is empty')
            return render(request, 'order/error_page.html', {'error': error})

class Order_Detail(View):
    def get(self, request, pk):
        try:
            order = Order.objects.get(pk=pk)
            return render(request, 'order/order_detail.html', {'object': order})
        except  Order.DoesNotExist:
            error = _('There is no such product')
            return render(request, 'order/error_page.html', {'error':error})

@staff_member_required
def admin_order_detail(request, pk):
    try:
        order = Order.objects.get(pk=pk)
        return render(request,'admin/orders/order/detail.html',{'order': order})
    except  Order.DoesNotExist:
        error = _('There is no such product')
        return render(request, 'order/error_page.html', {'error': error})

@staff_member_required
def admin_order_pdf(request, pk):
    order = get_object_or_404(Order, pk=pk)
    html = render_to_string('admin/orders/order/pdf.html', {'order': order})
    response = HttpResponse(content_type='application/pdf')
    response['Content-Disposition'] = f'filename=order_{order.pk}.pdf'
    stylesheets=[weasyprint.CSS(settings.STATIC_ROOT / 'order/css/pdf.css')]
    weasyprint.HTML(string=html).write_pdf(response,stylesheets=stylesheets)
    return response

order/templates/order/created_order.html
{% extends 'order/order_detail.html' %}
{% load i18n %}
{% load static %}

{% block content %}
<a href="{% url 'catalog:catalog_view' %}" class="btn btn-secondary mb-3">{% trans 'Back' %}</a>
<div class="card">
    <div class="card-body">
        <h1 class="card-title">{% trans 'Thank You' %}</h1>
        <p class="card-text">
            {% trans 'Order was placed successfully. We sent a letter with the order number to your e-mail.' %}
        </p>
    </div>
</div>
{% endblock content %}

order/templates/order/error_page.html
{% extends 'order/order_detail.html' %}
{% load i18n %}
{% load static %}

{% block content %}
<div class="alert alert-danger" role="alert">
    <h4 class="alert-heading">{% trans 'We apologize' %}</h4>
    <p>{{ error }}</p>
</div>
{% endblock content %}

order/templates/order/order_create.html
{% extends 'order/order_detail.html' %}
{% load i18n %}
{% load static %}

{% block content %}
<form method="post" enctype="multipart/form-data" class="form-group">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="btn btn-primary">{% trans 'send' %}</button>
</form>
{% endblock content %}

order/templates/order/order_detail.html
{% load i18n %}
{% load static %}

<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% trans 'Order details' %}{% endblock title %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
</head>
<body class="container mt-4">

{% block content %}
    <div class="card mb-4">
        <div class="card-header">
            <h2 class="mb-0">{% trans 'Order Details' %}</h2>
        </div>
        <div class="card-body">
            <p><strong>{% trans 'Address' %}:</strong> {{ object.address }}</p>
            <p><strong>{% trans 'First Name' %}:</strong> {{ object.first_name }}</p>
            <p><strong>{% trans 'Last Name' %}:</strong> {{ object.last_name }}</p>
            <p><strong>{% trans 'Email' %}:</strong> {{ object.email }}</p>
            <p><strong>{% trans 'City' %}:</strong> {{ object.city }}</p>
            <p><strong>{% trans 'Order Date' %}:</strong> {{ object.created }}</p>
            <p><strong>{% trans 'Total Order Cost' %}:</strong> ${{ object.total_order_cost }}</p>

            <p class="fw-bold text-{{ object.paid|yesno:'success,danger' }}">
                {% if object.paid %}
                    {% trans 'Paid' %}
                {% else %}
                    {% trans 'Unpaid' %}
                {% endif %}
            </p>
        </div>
    </div>

    <h3 class="mb-3">{% trans 'Goods' %}</h3>
    <div class="row">
        {% for item in object %}
            <div class="col-md-6 col-lg-4 mb-3">
                <div class="card h-100">
                    <div class="card-body">
                        <p class="card-title font-weight-bold">{{ item.product.name }} ({{ item.quantity }})</p>
                        <p class="card-text">{% trans 'Cost' %}: ${{ item.price }}</p>
                        <p class="card-text">{% trans 'Total Cost' %}: ${{ item.total_item_cost }}</p>
                        <a href="{% url 'catalog:product_detail' pk=item.product.pk slug=item.product.slug %}" class="btn btn-primary">{% trans 'More details' %}</a>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>

{% endblock content %}

    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.3/dist/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>

</body>
</html>

order/templates/order/order_history.html
{% extends 'order/order_detail.html' %}
{% load i18n %}
{% load static %}

{% block content %}
<div class="list-group">
    {% if objects %}
        {% for object in objects %}
            <div class="list-group-item">
                <p>{{ object.created }}</p>
                <p>{{ object.address }}</p>
                <a href="{% url 'order:order_detail' pk=object.pk %}" class="btn btn-info">{% trans 'More details' %}</a>
            </div>
            {% if not forloop.last %}
                <hr>
            {% endif %}
        {% endfor %}
    {% else %}
        <p>{% trans 'No orders yet' %}</p>
    {% endif %}
</div>
{% endblock content %}