cart/urls.py
from django.urls import path

from cart.views import cart_detail, cart_add, cart_remove, cart_add_one, cart_remove_one, clear_cart

app_name = 'cart'

urlpatterns = [
    path('', cart_detail, name='cart_detail'),
    path('add/<int:pk>/', cart_add, name='cart_add'),
    path('remove/<int:pk>/', cart_remove, name='cart_remove'),
    path('add_one/<int:pk>/', cart_add_one, name='cart_add_one'),
    path('remove_one/<int:pk>/', cart_remove_one, name='cart_remove_one'),
    path('clear/', clear_cart, name='clear_cart'),
]

catalog/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path
from catalog.views import *

app_name = 'catalog'

urlpatterns = [
    path('', Product_Catalog.as_view(), name='catalog_view'),
    path('delete_review/<int:pk>/', Delete_Review.as_view(), name='delete_review'),
    path('create_product/', Create_Product.as_view(), name='create_product'),
    path('detail_product/<int:pk>/<str:slug>/', Product_Detail.as_view(), name='product_detail'),
    path('update_product/<int:pk>/', Update_Product.as_view(), name='update_product'),
    path('delete_product/<int:pk>/', Delete_Product.as_view(), name='delete_product'),

    path('brand_list/', Brand_List.as_view(), name='brand_list'),
    path('create_brand/', Create_Brand.as_view(), name='create_brand'),
    path('detail_brand/<int:pk>/', Brand_Detail.as_view(), name='brand_detail'),
    path('update_brand/<int:pk>/', Update_Brand.as_view(), name='update_brand'),
    path('delete_brand/<int:pk>/', Delete_Brand.as_view(), name='delete_brand'),

    path('create_category/', Create_Category.as_view(), name='create_category'),
    path('delete_category/<int:pk>/', Delete_Category.as_view(), name='delete_category'),
    path('translate_category/<int:pk>/', Translate_Category.as_view(), name='translate_category'),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pet_project/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf.urls.i18n import i18n_patterns
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = i18n_patterns(
    re_path(r'^admin/', admin.site.urls),
    re_path(r'^', include("main_app.urls", namespace='main_app')),
    re_path(r'^catalog/', include("catalog.urls", namespace='catalog')),
    re_path(r'^cart/', include("cart.urls", namespace='cart')),
    re_path(r'^order/', include("order.urls", namespace='order')),
    re_path(r'^coupon/', include('coupon.urls', namespace='coupon')),
    re_path(r'^rosetta/', include('rosetta.urls')),
)

urlpatterns += [
    path('payment/', include('payment.urls', namespace='payment'))
]# отдельно чтобы не было в i18n_patterns

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

catalog/models.py
from enum import Enum
from django.contrib.auth import get_user_model
from django.core.validators import MinValueValidator
from django.db import models
from django.utils.translation import gettext_lazy as _
from parler.models import TranslatedFields, TranslatableModel

User = get_user_model()

# Create your models here.

size_choices = [
    ('XXS', 'XX Small'),
    ('XS', 'X Small'),
    ('S', 'Small'),
    ('M', 'Medium'),
    ('L', 'Large'),
    ('XL', 'X Large'),
    ('XXL', 'XX Large'),
    ('XXXL', 'XXX Large')
]

class Brand(TranslatableModel):
    slug = models.SlugField(max_length=200, db_index=True, unique=True)
    name = models.CharField(verbose_name=_('name'), max_length=100, db_index=True)
    translations = TranslatedFields(
        description=models.TextField(verbose_name=_('description'))
    )
    image = models.ImageField(verbose_name=_('image'), upload_to='brand_images/', blank=True)

    def __str__(self):
        return self.name

    class Meta:
        ordering = ('-pk',)
        verbose_name = _('Brand')
        verbose_name_plural = _('Brands')

class Category(TranslatableModel):
    translations = TranslatedFields(
        slug=models.SlugField(max_length=200, db_index=True, unique=True),
        name=models.CharField(verbose_name=_('name'), max_length=100, db_index=True, unique=True),
    )

    def __str__(self):
        return self.name

    class Meta:
        ordering = ('-pk',)
        verbose_name = _('Category')
        verbose_name_plural = _('Categories')

class Product(TranslatableModel):
    translations = TranslatedFields(
        slug = models.SlugField(max_length=200, db_index=True),
        name = models.CharField(verbose_name=_('name'), max_length=200),
        description = models.TextField(verbose_name=_('description')),
    )
    category = models.ForeignKey(Category, on_delete=models.CASCADE, verbose_name=_('category'))
    brand = models.ForeignKey(Brand, on_delete=models.CASCADE, verbose_name=_('brand'), blank=True, null=True)
    price = models.DecimalField(verbose_name=_('price'), max_digits=10, decimal_places=2, validators=[MinValueValidator(0)])
    size = models.CharField(verbose_name=_('size'), max_length=100, choices=size_choices, default='M')
    image = models.ImageField(verbose_name=_('image'), upload_to='clothes_images/', blank=True)
    availability = models.BooleanField(verbose_name=_('availability'), default=True)
    created = models.DateTimeField(verbose_name=_('created'), auto_now=True)

    def __str__(self):
        return self.name

    class Meta:
        ordering = ('-created',)
        verbose_name = _('Product')
        verbose_name_plural = _('Products')

class Review(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE, blank=True, verbose_name=_('product'))
    author = models.ForeignKey(User, on_delete=models.CASCADE, blank=True, verbose_name=_('author'))
    text = models.TextField(verbose_name=_('text'))
    date = models.DateTimeField(verbose_name=_('date'), auto_now=True, blank=True)
    parent = models.ForeignKey('self', verbose_name=_('parent'), on_delete=models.CASCADE, blank=True, null=True)# blank может быть не заполнено в формах null может быть не заполнено в самой модели и будет заменено на NULL(нужно для date и foreignkeyfield)

    def get_child_reviews(self):
        return Review.objects.filter(parent=self).order_by('date')

    def __str__(self):
        return f"{self.author.username} - {self.product} - {self.date}"

    class Meta:
        ordering = ('-date',)
        verbose_name = _('Review')
        verbose_name_plural = _('Reviews')

catalog/forms.py
from django import forms
from django.utils.translation import gettext_lazy as _
from parler.forms import TranslatableModelForm

from catalog.models import Product, Review, Category, Brand

class BrandForm(TranslatableModelForm):
    class Meta:
        model = Brand
        fields = ('name', 'description', 'image')

class CategoryForm(TranslatableModelForm):
    class Meta:
        model = Category
        fields = ('name',)

class ProductForm(TranslatableModelForm):
    class Meta:
        fields = ('name', 'description', 'image', 'category', 'brand', 'price', 'size', 'availability')
        model = Product

class ReviewForm(forms.ModelForm):
    class Meta:
        fields = ('product', 'author', 'text',)
        model = Review
        widgets = {
            'text': forms.Textarea(attrs={'id': 'contactcomment'}),
        }

catalog/views.py
from urllib.parse import urlencode
from django.core.exceptions import ObjectDoesNotExist
from django.core.paginator import Paginator
from django.db import IntegrityError
from django.http import JsonResponse
from django.shortcuts import render, redirect, get_object_or_404
from django.template.loader import render_to_string
from django.views import View
from cart.forms import CartAddProductForm
from catalog.forms import ProductForm, ReviewForm, CategoryForm, BrandForm
from catalog.models import Product, Review, Category, Brand
from django.utils.translation import gettext_lazy as _
from transliterate import slugify as transliterate_slugify
from django.utils.text import slugify
from catalog.recommender import Recommender
from django.contrib.auth.decorators import user_passes_test
from django.utils.decorators import method_decorator
from django.urls import reverse
from django.shortcuts import render
from django.http import HttpResponse
import logging
import time

logger = logging.getLogger(__name__)

# Create your views here.

def is_admin(user):
    return user.is_authenticated and user.is_staff

class Product_Catalog(View):

    def get(self, request):
        language = request.LANGUAGE_CODE
        categories = Category.objects.all()
        brands = Brand.objects.all()
        objects = Product.objects.filter(availability=True)

        category_slug = request.GET.get('category')
        if category_slug:
            category = Category.objects.get(translations__language_code=language, translations__slug=category_slug)
            objects = objects.filter(category=category)

        brand_slug = request.GET.get('brand')
        if brand_slug:
            brand = Brand.objects.get(slug=brand_slug)
            objects = objects.filter(brand=brand)

        search = request.GET.get('search')
        if search:
            objects = objects.filter(translations__name__icontains=search, translations__language_code=language)

        paginator = Paginator(objects, 30)
        page_number = request.GET.get('page')
        page_obj = paginator.get_page(page_number)

        query_params = request.GET.copy()
        if 'page' in query_params:
            del query_params['page']
        query_string = urlencode(query_params)

        context = {'categories': categories, 'brands': brands, 'objects': objects, 'page_obj': page_obj, 'query_string': query_string}
        return render(request, 'catalog/catalog_view.html', context)

class Product_Detail(View):
    def get(self, request, pk, slug):
        language = request.LANGUAGE_CODE
        try:
            product = Product.objects.get(pk=pk, translations__language_code=language, translations__slug=slug)
            cart_form = CartAddProductForm()
            review_form = ReviewForm()
            reviews = Review.objects.filter(product=product, parent__isnull=True)
            category = _(str(product.category))
            r = Recommender()
            recommended_products = r.suggest_products_for([product], 4)
            context = {'object': product, 'cart_form': cart_form, 'review_form': review_form, 'reviews': reviews, 'category': category, 'recommended_products': recommended_products}
            return render(request, 'catalog/product_detail.html', context)
        except Product.DoesNotExist:
            error = _('There is no such product')
            return render(request, 'catalog/error_page.html', {'error': error})

    def post(self, request, pk, slug):
        language = request.LANGUAGE_CODE
        form = ReviewForm(data=request.POST)
        if form.is_valid():
            review = form.save(commit=False)
            review.author = request.user
            review.product = Product.objects.get(pk=pk)
            if request.POST.get('parent', None):
                review.parent = Review.objects.get(pk=int(request.POST.get("parent")))
            review.save()
            return redirect('catalog:product_detail', pk=pk, slug=slug)
        else:
            object = Product.objects.get(pk=pk, translations__language_code=language,translations__slug=slug)
            return render(request, 'catalog/product_detail.html', {'form': form, 'object': object})

@method_decorator(user_passes_test(is_admin), name='dispatch')
class Delete_Review(View):
    def get(self, request, pk):
        try:
            object = Review.objects.get(pk=pk)
            return render(request, 'catalog/delete_review.html', {'object': object})
        except Review.DoesNotExist:
            error = _('There is no such review')
            return render(request, 'catalog/error_page.html', {'error': error})

    def post(self, request, pk):
        try:
            object = Review.objects.get(pk=pk)
            object.delete()
            return redirect('catalog:catalog_view')
        except Review.DoesNotExist:
            error = _('There is no such review')
            return render(request, 'catalog/error_page.html', {'error': error})

@method_decorator(user_passes_test(is_admin), name='dispatch')
class Create_Product(View):
    def get(self, request):
        return render(request, 'catalog/create_product.html', {'form': ProductForm()})

    def post(self, request):
        form = ProductForm(request.POST, request.FILES)
        if form.is_valid():
            object = form.save(commit=False)#создает запись не сохраняя ее в бд позволяя изменять ее
            translation_slug = transliterate_slugify(form.cleaned_data['name'])
            if not translation_slug:
                slug = slugify(form.cleaned_data['name'])
                if slug:
                    object.slug = slug
                else:
                    error = _('Incorrect form filling')
                    return render(request, 'catalog/error_page.html', {'error': error})
            elif translation_slug:
                object.slug = translation_slug
            object.save()
            return redirect('catalog:update_product', pk=object.pk)
        return render(request, 'catalog/create_product.html', {'form': form})

@method_decorator(user_passes_test(is_admin), name='dispatch')
class Update_Product(View):
    def get(self, request, pk):
        try:
            object = Product.objects.get(pk=pk)
            form = ProductForm(instance=object)
            context = {'form': form, 'object': object}
            return render(request, 'catalog/update_product.html', context)
        except Product.DoesNotExist:
            error = _('There is no such product')
            context = {'error': error}
            return render(request, 'catalog/error_page.html', context)

    def post(self, request, pk):
        try:
            product = Product.objects.get(pk=pk)
            form = ProductForm(request.POST, request.FILES, instance=product)
            if form.is_valid():
                product = form.save()#сначала обновляем продукт т.к если сохранить в конце объект перевода создастся повторно что приведет к ошибке уникальных ключей
                try:
                    object = product.translations.get(language_code=request.LANGUAGE_CODE, master_id = product.pk)
                    object.name=form.cleaned_data['name']
                    object.description=form.cleaned_data['description']
                except ObjectDoesNotExist:
                    object = product.translations.model(
                        language_code=request.LANGUAGE_CODE,
                        name=form.cleaned_data['name'],
                        description=form.cleaned_data['description'],
                        master_id=pk,
                    )
                translation_slug = transliterate_slugify(form.cleaned_data['name'])
                if not translation_slug:
                    slug = slugify(form.cleaned_data['name'])
                    if slug:
                        object.slug = slug
                    else:
                        error = _('Incorrect form filling')
                        return render(request, 'catalog/error_page.html', {'error': error})
                if translation_slug:
                    object.slug = translation_slug
                object.save()
                return redirect('catalog:update_product', pk=product.pk)
            else:
                return render(request, 'catalog/update_product.html', {'form': form, 'object': product})
        except Product.DoesNotExist:
            error = _('There is no such product')
            return render(request, 'catalog/error_page.html', {'error': error})
        except Exception as error:
            return render(request, 'catalog/error_page.html', {'error': error})

@method_decorator(user_passes_test(is_admin), name='dispatch')
class Delete_Product(View):
    def get(self, request, pk):
        try:
            object = Product.objects.get(pk=pk)
            return render(request, 'catalog/delete_product.html' , {'object': object})
        except Product.DoesNotExist:
            error = _('There is no such product')
            return render(request, 'catalog/error_page.html', {'error': error})

    def post(self, request, pk):
        try:
            object = Product.objects.get(pk=pk)
            object.delete()
            return redirect('catalog:catalog_view')
        except Product.DoesNotExist:
            error = _('There is no such product')
            return render(request, 'catalog/error_page.html', {'error': error})

class Brand_List(View):
    def get(self, request):
        objects = Brand.objects.all()

        paginator = Paginator(objects, 10)
        page_number = request.GET.get('page')
        page_obj = paginator.get_page(page_number)

        return render(request, 'catalog/brand_list.html', {'objects': objects, 'page_obj': page_obj})

@method_decorator(user_passes_test(is_admin), name='dispatch')
class Create_Brand(View):
    def get(self, request):
        return render(request, 'catalog/create_brand.html', {'form': BrandForm()})

    def post(self, request):

catalog/templates/catalog/brand_detail.html
{% extends 'catalog/catalog_view.html' %}
{% load static %}
{% load i18n %}

{% block title %}{% trans 'Brand details' %}{% endblock title %}

{% block content %}

<div class="container mt-5">
    <div class="row">
        <div class="col-12">
            <p><a href="{% url 'catalog:brand_list' %}" class="btn btn-secondary">{% trans 'Back' %}</a></p>
        </div>
    </div>
    <div class="row">
        <div class="col-12 text-center">
            <h2>{{ object.name }}</h2>
            <hr class="my-4" style="background-color: black;">
        </div>
    </div>

    <div class="row justify-content-center">
        <div class="col-md-6">
            <div class="card mb-4" style="word-break: break-all;">
                {% if object.image %}
                    <img src="{{ object.image.url }}" class="card-img-top" alt="Brand Image">
                {% else %}
                    <img src="{% static 'catalog/img/photo_2024-04-04_14-55-47.jpg' %}" class="card-img-top" alt="Brand Image">
                {% endif %}
                <div class="card-body">
                    <small>{% trans 'Description' %}</small>
                    <p class="card-text">{{ object.description }}</p>
                </div>
                {% if user.is_staff %}
                    <div class="card-footer text-center">
                        <a href="{% url 'catalog:update_brand' pk=object.pk %}" class="btn btn-primary mr-2">{% trans 'Update' %}</a>
                        <a href="{% url 'catalog:delete_brand' pk=object.pk %}" class="btn btn-danger">{% trans 'Delete' %}</a>
                    </div>
                {% endif %}
                <div class="card-footer text-center">
                    <a href="{% url 'catalog:catalog_view' %}?brand={{ object.slug }}" class="btn btn-success">{% trans 'Products' %}</a>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock content %}

catalog/templates/catalog/brand_list.html
{% extends 'catalog/catalog_view.html' %}
{% load static %}
{% load i18n %}

{% block title %}{% trans 'Brand list' %}{% endblock title %}

{% block content %}

    <div class="container mt-5">

    <div class="row">
        <div class="col-12">
            <p><a href="{% url 'catalog:catalog_view' %}" class="btn btn-secondary">{% trans 'Back' %}</a></p>
        </div>
    </div>

    <div class="row">
        <div class="col-12 text-center">
            <h2>{% trans 'Brands' %}</h2>
            <hr class="my-4" style="background-color: black;">
        </div>
    </div>

    <div class="row">
        {% for object in page_obj %}
            <div class="col-md-4 mb-4">
                <div class="card h-100">
                    {% if object.image %}
                        <img src="{{ object.image.url }}" class="card-img-top" alt="Brand Image" height="300">
                    {% else %}
                        <img src="{% static 'catalog/img/photo_2024-04-04_14-55-47.jpg' %}" class="card-img-top" alt="Brand Image" height="300">
                    {% endif %}
                    <div class="card-body">
                        <h5 class="card-title">{{ object.name }}</h5>
                        <p class="card-text">{{ object.description }}</p>
                    </div>
                    <div class="card-footer text-center">
                        <a href="{% url 'catalog:brand_detail' pk=object.pk %}" class="btn btn-secondary">{% trans 'More details' %}</a>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
    <hr style="background-color: black;">

    <nav aria-label="Page navigation">
        <ul class="pagination justify-content-center">
            {% if page_obj.has_previous %}
                <li class="page-item">
                    <a class="page-link" href="?page={{ page_obj.previous_page_number }}" aria-label="{% trans 'Previous' %}">
                        <span aria-hidden="true">&laquo;</span>
                        <span class="sr-only">{% trans 'Previous' %}</span>
                    </a>
                </li>
            {% endif %}
            {% for num in page_obj.paginator.page_range %}
                {% if page_obj.number == num %}
                    <li class="page-item active"><a class="page-link" href="#">{{ num }} <span class="sr-only">(current)</span></a></li>
                {% else %}
                    <li class="page-item"><a class="page-link" href="?page={{ num }}">{{ num }}</a></li>
                {% endif %}
            {% endfor %}
            {% if page_obj.has_next %}
                <li class="page-item">
                    <a class="page-link" href="?page={{ page_obj.next_page_number }}" aria-label="{% trans 'Next' %}">
                        <span aria-hidden="true">&raquo;</span>
                        <span class="sr-only">{% trans 'Next' %}</span>
                    </a>
                </li>
            {% endif %}
        </ul>
    </nav>

    </div>

{% endblock content %}

catalog/templates/catalog/product_detail.html
{% extends 'catalog/catalog_view.html' %}
{% load static %}
{% load i18n %}

{% block content %}
<div class="container mt-5">

    <div class="row mb-4">
        <div class="col-12">
            <p><a href="{% url 'catalog:catalog_view' %}" class="btn btn-secondary">{% trans 'Back' %}</a></p>
        </div>
    </div>

    <div class="row">
        <div class="col-md-6 col-12 mb-3">
            {% if object.image %}
                <img src="{{ object.image.url }}" class="img-fluid rounded" alt="Product Image">
            {% else %}
                <img src="{% static 'catalog/img/photo_2024-04-04_14-55-47.jpg' %}" class="img-fluid rounded" alt="Product Image">
            {% endif %}
        </div>
        <div class="col-md-6 col-12" style="word-break: break-all;">
            <h1>{{ object.name }}</h1>
            <p><strong>{% trans 'Description' %}:</strong> {{ object.description }}</p>
            <p><strong>{% trans 'Category' %}:</strong> {{ object.category }}</p>
            <p><strong>{% trans 'Brand' %}:</strong> {{ object.brand }}</p>
            <p><strong>{% trans 'Price' %}:</strong> {{ object.price }}</p>
            <p><strong>{% trans 'Size' %}:</strong> {{ object.size }}</p>
            <p><strong>{% trans 'Availability' %}:</strong> {{ object.availability }}</p>

            {% if user.is_staff %}
                <div class="mt-4">
                    <a href="{% url 'catalog:update_product' pk=object.pk %}" class="btn btn-outline-primary">{% trans 'Update' %}</a>
                    <a href="{% url 'catalog:delete_product' pk=object.pk %}" class="btn btn-outline-danger">{% trans 'Delete' %}</a>
                </div>
            {% endif %}

            <form action="{% url 'cart:cart_add' pk=object.pk %}" method="post" class="mt-4">
                {% csrf_token %}
                <div class="input-group mb-3">
                    {{ cart_form.quantity }}
                    <button type="submit" class="btn btn-primary">{% trans 'Add to cart' %}</button>
                </div>
            </form>
        </div>
    </div>

    {% if recommended_products %}
    <div class="row mt-5">
        <div class="col-12">
            <h3>{% trans 'Similar products' %}</h3>
        </div>
        {% for p in recommended_products %}
        <div class="col-md-3 col-sm-6 mb-4">
            <div class="card">
                {% if p.image %}
                    <img src="{{ p.image.url }}" class="card-img-top" alt="Product Image" height="250">
                {% else %}
                    <img src="{% static 'catalog/img/photo_2024-04-04_14-55-47.jpg' %}" class="card-img-top" alt="Product Image" height="250">
                {% endif %}
                <div class="card-body">
                    <h5 class="card-title">{{ p.name }}</h5>
                    <a href="{% url 'catalog:product_detail' pk=p.pk slug=p.slug %}" class="btn btn-primary">{% trans 'More details' %}</a>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
    {% endif %}

    <div class="row mt-5">
        <div class="col-12">
            <h3>{% trans 'Leave a review' %}</h3>
            <form method="post" enctype="multipart/form-data" class="mb-4" id="FormReview">
                {% csrf_token %}
                <input type="hidden" name="parent" id="contactparent" value="">
                <div class="mb-3">
                    {{ review_form.text }}
                </div>
                <button type="submit" class="btn btn-primary">{% trans 'Send' %}</button>
            </form>

            <h3>{% trans 'Reviews' %}</h3>
            {% if reviews %}
            <div class="list-group" style="word-break: break-word;">
                {% for review in reviews %}
                <div class="list-group-item d-flex flex-column flex-md-row mb-3">
                    <div class="d-flex align-items-start me-3">
                        {% if review.author.avatar %}
                            <img src="{{ review.author.avatar.url }}" class="rounded-circle me-3" alt="Avatar" style="width: 50px; height: 50px;">
                        {% else %}
                            <img src="{% static 'main_app/img/photo_2024-04-04_14-56-07.jpg' %}" class="rounded-circle me-3" alt="Avatar" style="width: 50px; height: 50px;">
                        {% endif %}
                    </div>
                    <div class="flex-fill">
                        <h5 class="mb-1">{{ review.author.username }}</h5>
                        <p class="mb-1">{{ review.text }}</p>
                        <p><small>{{ review.date }}</small></p>
                        <a href="#FormReview" class="btn btn-outline-primary btn-sm" onclick="AddReview('{{ review.author.username }}', '{{ review.pk }}')">{% trans 'Response' %}</a>
                        {% if user.is_staff %}
                            <a href="{% url 'catalog:delete_review' pk=review.pk %}" class="btn btn-outline-danger btn-sm">{% trans 'Delete' %}</a>
                        {% endif %}
                        {% if review.get_child_reviews %}
                        <div class="mt-3">
                            {% for child_review in review.get_child_reviews %}
                            <div class="list-group-item d-flex flex-column flex-md-row mb-3">
                                <div class="d-flex align-items-start me-3">
                                    {% if child_review.author.avatar %}
                                        <img src="{{ child_review.author.avatar.url }}" class="rounded-circle me-3" alt="Avatar" style="width: 50px; height: 50px;">
                                    {% else %}
                                        <img src="{% static 'main_app/img/photo_2024-04-04_14-56-07.jpg' %}" class="rounded-circle me-3" alt="Avatar" style="width: 50px; height: 50px;">
                                    {% endif %}
                                </div>
                                <div class="flex-fill">
                                    <h6 class="mb-1">{{ child_review.author.username }}</h6>
                                    <p class="mb-1">{{ child_review.text }}</p>
                                    <p><small>{{ child_review.date }}</small></p>
                                    {% if user.is_staff %}
                                        <a href="{% url 'catalog:delete_review' pk=child_review.pk %}" class="btn btn-outline-danger btn-sm">{% trans 'Delete' %}</a>
                                    {% endif %}
                                </div>
                            </div>
                            {% endfor %}
                        </div>
                        {% endif %}
                    </div>
                </div>
                {% endfor %}
            </div>
            {% else %}
            <p>{% trans 'No reviews yet' %}</p>
            {% endif %}
        </div>
    </div>
</div>
{% endblock content %}

{% block script %}
<script>
    function AddReview(username, pk) {
        document.getElementById("contactparent").value = pk;
        document.getElementById("contactcomment").value = `${username},`;
    }
</script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"></script>
{% endblock script %}

catalog/templates/catalog/update_brand.html
{% extends 'catalog/catalog_view.html' %}
{% load static %}
{% load i18n %}

{% block content %}

<div class="col-12 text-center">
    <h2>{% trans 'Update brand' %}</h2>
    <hr class="my-4" style="background-color: black;">
</div>
<div class="container mt-5">

    <div class="row">
        <div class="col-12">
            <p><a href="{% url 'catalog:brand_detail' pk=object.pk %}" class="btn btn-secondary">{% trans 'Back' %}</a></p>
        </div>
    </div>

    <div class="row">
        {% get_current_language as LANGUAGE_CODE %}
        {% get_available_languages as LANGUAGES %}
        {% get_language_info_list for LANGUAGES as languages %}

        <div class="row mb-4">
            <div class="col-12 text-center">
                <p><strong>{% trans "Language" %}:</strong></p>
                <ul class="list-inline">
                    {% for language in languages %}
                        <li class="list-inline-item">
                            <a href="/{{ language.code }}/catalog/update_brand/{{ object.pk }}/" {% if language.code == LANGUAGE_CODE %} class="selected"{% endif %}>
                                <button class="btn btn-outline-primary">{{ language.name_local }}</button>
                            </a>
                        </li>
                    {% endfor %}
                </ul>
            </div>
        </div>
        <div class="row justify-content-center">
        <div class="col-md-8">
            <form method="post" enctype="multipart/form-data" class="p-4" style="background-color: transparent;">
                {% csrf_token %}
                {{ form.as_p }}
                <div class="text-center">
                    <button type="submit" class="btn btn-primary">{% trans 'save' %}</button>
                </div>
            </form>
        </div>
        </div>
    </div>
</div>
{% endblock content %}